com:
  ziyao:
    crypto:
      cipher:
        types: sm4
        sm4:
          key: 13f70890272c40c07d85b15e5d532bd5
          iv: b18451cd68969ad9ec78f7c700370eea
          mode: CBC
      config:
        # 配置文件输入路径
        location-in: /resources/input
        # 配置文件输出路径
        location-out: /resources/output
      keys:
        - spring.datasource.password
        - spring.datasource.url
        - spring.datasource.username
        - spring.cloud.nacos.discovery.server-addr
        - spring.data.redis.host
        - spring.data.redis.port
        - spring.data.redis.password